name: Hello
on:
  push: ~

jobs:
  self-hosted-hello:
    timeout-minutes: 5
    runs-on:
    - self-hosted
    - Linux
    steps:
    - uses: actions/checkout@v2
    - name: Hello
      run: echo "Hello World"
