name: Hello
on:
  workflow_dispatch: ~

jobs:
  self-hosted-hello:
    timeout-minutes: 5
    runs-on:
    - self-hosted
    - linux
    - default-runner
    steps:
    - uses: actions/checkout@v2
    - name: Hello
      run: echo "Hello World"
