name: Hello GPU
on:
  workflow_dispatch: ~

jobs:
  self-hosted-hello:
    timeout-minutes: 5
    runs-on:
    - self-hosted
    - linux
    - gpu-runner
    steps:
    - uses: actions/checkout@v2
    - name: Hello
      run: echo "Hello World ! I have a GPU !"
